services:
  db:
    image: pgvector/pgvector:pg16
    # Increase SHM size, default is only 64MB
    shm_size: 24gb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: 407-ki
    ports:
      - "127.0.0.1:5432:5432"
